### ISSUE TITLE
About render back

### ISSUE THREAD

**Issue by MontaEllis** [ylabo0717/iPhone-3D-Reconstruction#1]
Hi, 
   Your work inspits me a lot! But I wonder if you can render back to rgb image to show the corresponding relationship?

**Comment by ylabo0717** [comment]
Hi, @MontaEllis. Thanks for your comment.
Do you mean you want the RGB-D dataset?
If so, I have uploaded it below. You can download it if you like.

https://drive.google.com/file/d/1VpPpv27ai7g-fK3EEVo5zacZPFd073t6/view?usp=sharing
