### ISSUE TITLE
Can I get pose data whilst streaming through USB?

### ISSUE THREAD

**Issue by knsjoon** [ylabo0717/iPhone-3D-Reconstruction#2]
I realized that streaming through USB does not save any recordings so there is no way of getting pose data. 
Any remedy for this?

Thank you for the code.

**Comment by ylabo0717** [comment]
@knsjoon Thanks for your question.
But I don't know how to get camera pose data whilst streaming through USB.
Unfortunately, [Record3D](https://github.com/marek-simonik/record3d) does not seem to support the acquisition of camera pose data.
I can't find the code to get the camera pose data in Record3D.

(Refer)
https://github.com/marek-simonik/record3d/blob/master/include/record3d/Record3DStream.h

**Comment by knsjoon** [comment]
@ylabo0717 Yes.. I asked the creator of the app directly and he indeed confirmed that it is not possible to obtain the pose data. 
But still! I appreciate your code so thank you very much : )
