### ISSUE TITLE
get error "Singular 6x6 linear system detected, tracking failed." with your dataset

### ISSUE THREAD

**Issue by Wulder** [ylabo0717/iPhone-3D-Reconstruction#3]
Hello, do you know anything about it ?

i get error when i use your dataset

I use open3d 0.15.0

Full error:

Exception in thread UpdateMain:
Traceback (most recent call last):
File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
self.run()
File "/usr/lib/python3.10/threading.py", line 946, in run
self._target(*self._args, **self._kwargs)
File "/home/USERNAME/PycharmProjects/Escan/t_reconstruction_system/dense_slam_gui.py", line 384, in update_main
result = self.model.track_frame_to_model(
RuntimeError: [Open3D Error] (void open3d::t::pipelines::kernel::DecodeAndSolve6x6(const open3d::core::Tensor&, open3d::core::Tensor&, float&, int&)) /home/tUSERNAME/Open3D/cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp:145: Singular 6x6 linear system detected, tracking failed.

**Comment by ylabo0717** [comment]
@Wulder 
The same problem was reproduced by OnlineSLAMRGBD.exe in Open3D 0.16.0, sorry, but I don't know the cause.
The problem has been corrected in the new data, so if you would like to try the following data.

https://drive.google.com/file/d/15BpnsuWo2beH8rNDpTC-3vjyt6cv0q4B/view?usp=sharing
