### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by lollo90ollol** [ylabo0717/iPhone-3D-Reconstruction#4]
When i launch the file reconstruction.bat the config.json is missing for the reconstruction?? What is an example of config file?? where can i find it??

**Comment by ylabo0717** [comment]
@lollo90ollol Thank you for your comment.
The iphone_rgbd_recorder.py saves the config.json along with the image data when recording.

Please refer to the sample below.

https://drive.google.com/file/d/15BpnsuWo2beH8rNDpTC-3vjyt6cv0q4B/view?usp=sharing
